const ModuleFederationPlugin = require("webpack/lib/container/ModuleFederationPlugin");

module.exports = {
    output: {
        publicPath: "http://localhost:5200/",
        uniqueName: "shell"
    },
    optimization: {
        // Only needed to bypass a temporary bug
        runtimeChunk: false
    },
    plugins: [
        new ModuleFederationPlugin({

            // For remotes (please adjust)
            name: "shell",
            library: {
                type: "var",
                name: "shell"
            },
            // file generated by webpack when building the remote.
            // Webpack loads it at runtime to get all the information
            // needed for interacting with the micro-frontend.
            filename: "remoteEntry.js",
            exposes: {
                './ShellModule': './projects/shell/src/app/shell/shell.module.ts',
                './Module': './projects/shell/src/app/app.module.ts'
            },


            shared: ["@angular/core", "@angular/common", "@angular/router"]
        })
    ],
};
